### ISSUE TITLE
`./airprint_bridge.sh -t` failed

### ISSUE THREAD

**Issue by ice6** [sapireli/AirPrint_Bridge#2]
when I run `./airprint_bridge.sh -t`, it shows:

```
Listing local shared printers...
lpoptions：无法添加打印机或实例：Undefined error: 0
No shared printers found.
Test aborted: No suitable printers found.
```

run `lpoptions` directly:
```
bing@xs-macmini AirPrint_Bridge % lpoptions
copies=1 device-uri=usb://Brother/HL-2260D?serial=E80121E0N234189 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=1733152708 marker-colors=#000000 marker-levels=70 marker-names=Black marker-types=toner number-up=1 printer-commands=ReportLevels,PrintSelfTestPage,PJLBidirectional,PJLWrite,PJLRead printer-info='Brother HL-2260D' printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location=xs-macmini printer-make-and-model='Brother HL-2260D CUPS' printer-state=3 printer-state-change-time=1733545623 printer-state-reasons=none printer-type=8425556 printer-uri-supported=ipp://localhost/printers/Brother_HL_2260D
```

this is my printer:

<img width="668" alt="macos printer setting" src="https://github.com/user-attachments/assets/1e1db635-504b-4601-a3b6-f53f4c423c16">

you are a hero to share a software like this.

**Comment by sapireli** [comment]
Download the latest version, i made a change enforcing English locale for lpstat parsing. Let me know if this resolves your issue if not can you post the output of  `lpstat -p`

**Comment by sapireli** [comment]
@ice6 any luck?

**Comment by ice6** [comment]
@sapireli thank you. no luck, because my system is chinese language. the `lpstat -p` command output like this:
```
打印机Brother_HL_2260D闲置，启用时间始于Sat Dec 14 21:22:33 2024
```
so `awk '{print $2}'` can not parse my machine's name correctly.

I tried the following commands which is given by `chatgpt`
```
LANG=C lpstat -p
LANG=en_US.UTF-8 lpstat -p
LC_ALL=C lpstat -p
 ```
the terminal still output same message.

**Comment by ice6** [comment]
@sapireli 

according to this link, I found the solution in MacOS.

https://apple.stackexchange.com/questions/474971/change-output-language-of-internal-commands-like-lpstat

```
SOFTWARE= LANG=C lpstat -a
```

it works!

I install the software successfully and it works!

Now, I can print from iOS device through my old mac mini 2014.

thanks for this wonderful tool.
